#!/bin/bash
# Container entrypoint.
#   1) Export runtime env vars to /etc/environment so cron jobs see them
#      (cron does NOT inherit the container's env block).
#   2) Run DB migrations once (idempotent).
#   3) Ensure runtime dirs exist on the mounted volumes.
#   4) Hand off to `cron -f` as PID 1.
set -euo pipefail

LOG_PREFIX="[entrypoint $(date -u +%FT%TZ)]"
log() { echo "${LOG_PREFIX} $*"; }

# ---------------------------------------------------------------------------
# 1. Make container env visible to cron jobs
# ---------------------------------------------------------------------------
log "exporting env vars to /etc/environment for cron"
# Whitelist: only known prefixes get exported. Avoids leaking PATH/HOME etc.
ENV_WHITELIST='^(TZ|PYTHONUNBUFFERED|LLM_BACKEND|BROWSER_BACKEND|DRY_RUN|MOONSHOT_API_KEY|ANTHROPIC_API_KEY|TWITTER_HANDLE|TWITTER_COOKIE_FILE|TWITTER_XIAOHAO_COOKIE_FILE|XUEQIU_COOKIE_FILE|DISCORD_BOT_TOKEN|DISCORD_DRAFT_CHANNEL_ID|DISCORD_OWNER_USER_ID|DISCORD_APPROVAL_MODE|ALERT_CHANNEL_ID|ALERT_THREAD_ID|FUTU_.*|MOONSHOT_.*|PEPPERBOT_.*|DB_PATH|LOG_DIR)='

# Wipe previous (in case of restart) then re-emit.
{
    echo "# pepperbot env (regenerated by entrypoint)"
    printenv | grep -E "${ENV_WHITELIST}" | sed 's/^/export /'
} > /etc/environment

# Cron itself sources /etc/environment but expects `KEY=VALUE` lines (no export).
# Rewrite it that way for cron, and keep the `export ...` variant in /etc/profile.d
# so an interactive `docker exec` shell also sees the values.
printenv | grep -E "${ENV_WHITELIST}" > /etc/environment
cp /etc/environment /etc/profile.d/pepperbot-env.sh 2>/dev/null || true
# Restrict to root-only; cron (running as root) still reads it.
chmod 600 /etc/environment /etc/profile.d/pepperbot-env.sh 2>/dev/null || true

# ---------------------------------------------------------------------------
# 2. Make sure runtime dirs exist on bind-mounted volumes
# ---------------------------------------------------------------------------
mkdir -p /app/logs /app/data /app/tmp_images

# ---------------------------------------------------------------------------
# 3. Run migrations (idempotent). If it fails, alert and bail.
# ---------------------------------------------------------------------------
log "running DB migrations"
if ! python -m src.migrations.runner >> /app/logs/migrations.log 2>&1; then
    log "ERROR: migrations failed"
    # Reuse Discord bot for the alert (no separate webhook).
    ch="${ALERT_CHANNEL_ID:-${DISCORD_DRAFT_CHANNEL_ID:-}}"
    if [ -n "${DISCORD_BOT_TOKEN:-}" ] && [ -n "${ch}" ]; then
        url="https://discord.com/api/v10/channels/${ch}/messages"
        [ -n "${ALERT_THREAD_ID:-}" ] && url="${url}?thread_id=${ALERT_THREAD_ID}"
        curl -fsS -X POST \
            -H "Authorization: Bot ${DISCORD_BOT_TOKEN}" \
            -H 'Content-Type: application/json' \
            -d '{"content":":rotating_light: pepperbot startup failed: migrations runner exited non-zero"}' \
            "${url}" >/dev/null 2>&1 || true
    fi
    exit 1
fi

# ---------------------------------------------------------------------------
# 4. Cron in foreground (becomes PID 1 via exec)
# ---------------------------------------------------------------------------
log "starting cron in foreground"
exec cron -f
